# https://taskfile.dev/
version: "3"

env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  install-flit:
    status:
      - which flit
    cmds:
      - python3 -m pip install --break-system-packages flit

  release:
    desc: build and upload release
    cmds:
      - task: install-flit
      - which gh
      - rm -rf dist
      - grep -F {{.CLI_ARGS}} svg/__init__.py
      - git add svg/__init__.py
      - git commit -m "bump version"
      - git tag {{.CLI_ARGS}}
      - flit publish
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
      - gh release upload {{.CLI_ARGS}} ./dist/*

  examples:
    desc: run and actualize all examples
    env:
      PYTHONPATH: .
    cmds:
      - python3 examples/animate.py           > examples/animate.svg
      - python3 examples/animate_transform.py > examples/animate_transform.svg
      - python3 examples/grid3.py             > examples/grid3.svg
      - python3 examples/grid4.py             > examples/grid4.svg
      - python3 examples/shapes.py            > examples/shapes.svg
      - python3 examples/text.py              > examples/text.svg
      - python3 examples/transform.py         > examples/transform.svg
